
Main.class: 
	javac Main.java Mision.java Jugador.java Mago.java Guerrero.java Druida.java NPC.java Bueno.java Malo.java Neutro.java Enemigo.java Monstruo.java Jefe_Final.java Tierra.java Montana.java Planicie.java Bosque.java

run:
	java Main.class Mision.class Jugador.class Mago.class Guerrero.class Druida.class NPC.class Bueno.class Malo.class Neutro.class Enemigo.class Monstruo.class Jefe_Final.class Tierra.class Montana.class Planicie.class Bosque.class

clear:
	rm *.class

clean:
	rm *.class