
Main.class: 
	javac Main.java Mision.java Jugador.java Mago.java Guerrero.java Druida.java NPC.java Bueno.java Malo.java Neutro.java Enemigo.java Monstruo.java Jefe_Final.java Tierra.java Montana.java Planicie.java Bosque.java



clear:
	rm *.class

clean:
	rm *.class