
Main.class: Jugador.class NPC.class Enemigo.class Tierra.class
	javac Main.java Jugador.class NPC.class Enemigo.class Tierra.class

Jugador.class: Jugador.java Mago.java Guerrero.java Druida.java Mision.java
	javac Jugador.java Mago.java Guerrero.java Druida.java Mision.java

NPC.class: NPC.java Bueno.java Malo.java Neutro.java Jugador.class
	javac NPC.java Bueno.java Malo.java Neutro.java Jugador.class

Enemigo.class: Monstruo.java Jefe_Final.java Jugador.class
	javac Monstruo.java Jefe_Final.java Jugador.class

Tierra.class: Montana.java Planicie.java Bosque.java
	javac Montana.java Planicie.java Bosque.java

clear:
	rm *.class

clean:
	rm *.class